# Copyright 2026 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  labels:
    edge-type: compute
    role: hackathon-infra
  name: lag1
  namespace: eda
spec:
  description: Multi-homed device connected to port 2
  enabled: true
  encapType: Dot1q
  ethernet:
    standbySignaling: LACP
  lag:
    lacp:
      adminKey: 12
      interval: Fast
      lacpFallback:
        mode: Static
      mode: Active
      systemMAC: "00:00:00:00:00:12"
    minLinks: 1
    multihoming:
      esi: 01:DC:01:12:12:12:12:00:00:01
      mode: AllActive
    type: LACP
  lldp: false
  members:
    - aggregateID: "1"
      enabled: true
      interface: ethernet-1-2
      node: g${INSTANCE_ID}-leaf11
    - aggregateID: "1"
      enabled: true
      interface: ethernet-1-2
      node: g${INSTANCE_ID}-leaf12
    - aggregateID: "1"
      enabled: true
      interface: ethernet-1-2
      node: g${INSTANCE_ID}-leaf13
  type: LAG
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  labels:
    edge-type: compute
    role: hackathon-infra
  name: leaf11-client11
  namespace: eda
spec:
  enabled: true
  encapType: Dot1q
  lldp: false
  members:
    - enabled: true
      interface: ethernet-1-1
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf11
  type: Interface
  description: "leaf11-client11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  labels:
    role: hackathon-infra
    edge-type: compute
  name: leaf13-client13
  namespace: eda
spec:
  enabled: true
  encapType: Dot1q
  lldp: false
  members:
    - enabled: true
      interface: ethernet-1-3
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf13
  type: Interface
  description: "leaf13-client13"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine11-ethernet-1-31
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: Interface
  description: "spine11-ethernet-1-31"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine11-ethernet-1-32
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: Interface
  description: "spine11-ethernet-1-32"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine12-ethernet-1-31
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: Interface
  description: "spine12-ethernet-1-31"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine12-ethernet-1-32
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: Interface
  description: "spine12-ethernet-1-32"
