apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    edge-type: compute
    role: hackathon-infra
  name: lag1
  namespace: eda
spec:
  description: Multi-homed device connected to port 2
  enabled: true
  encapType: dot1q
  ethernet:
    standbySignaling: lacp
  lag:
    lacp:
      adminKey: 12
      interval: fast
      lacpFallback:
        mode: static
        timeout: 60
      mode: active
      systemIdMac: "00:00:00:00:00:12"
      systemPriority: 32768
    minLinks: 1
    multihoming:
      esi: 01:DC:01:12:12:12:12:00:00:01
      mode: all-active
      reloadDelayTimer: 100
      revertive: false
      preferredActiveNode: ""
    type: lacp
  lldp: false
  members:
    - aggregateId: "1"
      enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf11
    - aggregateId: "1"
      enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf12
    - aggregateId: "1"
      enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf13
  type: lag
  mtu: null
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    edge-type: compute
    role: hackathon-infra
  name: leaf11-client11
  namespace: eda
spec:
  enabled: true
  encapType: dot1q
  lldp: false
  members:
    - enabled: true
      interface: ethernet-1-1
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf11
  type: interface
  description: "leaf11-client11"
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  labels:
    role: hackathon-infra
    edge-type: compute
  name: leaf13-client13
  namespace: eda
spec:
  enabled: true
  encapType: dot1q
  lldp: false
  members:
    - enabled: true
      interface: ethernet-1-3
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf13
  type: interface
  description: "leaf13-client13"
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  name: spine11-ethernet-1-31
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: interface
  description: "spine11-ethernet-1-31"
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  name: spine11-ethernet-1-32
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: interface
  description: "spine11-ethernet-1-32"
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  name: spine12-ethernet-1-31
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: interface
  description: "spine12-ethernet-1-31"
---
apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  name: spine12-ethernet-1-32
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  enabled: true
  encapType: "null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: interface
  description: "spine12-ethernet-1-32"
