# Copyright 2026 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: routingpolicies.eda.nokia.com/v1
kind: Policy
metadata:
  name: accept-all
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  defaultAction:
    policyResult: Accept
