# Copyright 2026 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: routing.eda.nokia.com/v1
kind: DefaultInterface
metadata:
  name: interface-spine11-ethernet-1-31
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  defaultRouter: router-g${INSTANCE_ID}-spine11
  interface: spine11-ethernet-1-31
  unnumbered: IPv6
---
apiVersion: routing.eda.nokia.com/v1
kind: DefaultInterface
metadata:
  name: interface-spine11-ethernet-1-32
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  defaultRouter: router-g${INSTANCE_ID}-spine11
  interface: spine11-ethernet-1-32
  unnumbered: IPv6
---
apiVersion: routing.eda.nokia.com/v1
kind: DefaultInterface
metadata:
  name: interface-spine12-ethernet-1-31
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  defaultRouter: router-g${INSTANCE_ID}-spine12
  interface: spine12-ethernet-1-31
  unnumbered: IPv6
---
apiVersion: routing.eda.nokia.com/v1
kind: DefaultInterface
metadata:
  name: interface-spine12-ethernet-1-32
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  defaultRouter: router-g${INSTANCE_ID}-spine12
  interface: spine12-ethernet-1-32
  unnumbered: IPv6
