# Copyright 2026 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: services.eda.nokia.com/v2
kind: BridgeDomain
metadata:
  name: macvrf11
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  # TODO revisit this bd config before 25.12
  #description: MAC-VRF for connectivity via the GRT of the WAN
  evi: 1
  eviPool: evi-pool
  exportTarget: target:65000:11
  importTarget: target:65000:11
  type: EVPNVXLAN
  encapOptions:
    vxlan:
      tunnelIndexPool: tunnel-index-pool
      vni: 11
      vniPool: vni-pool
