# --- Configlets IRB GRT ---
# this configlet creates a dedicated IRB for the MAC-VRF
# that need to be connected to the GRT. This is not
# supported yet in EDA
apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: irb-grt
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  endpointSelector:
    - eda.nokia.com/role=leaf
  operatingSystem: srl
  configs:
    - path: .interface{.name=="irb1"}
      operation: Create
      config: |-
        {
            "name": "irb1",
            "subinterface": [
                {
                    "index": 1,
                    "description": "irb1.1",
                    "ipv4": {
                        "admin-state": "enable",
                        "address": [
                            {
                                "ip-prefix": "10.64.30.1/24",
                                "anycast-gw": true
                            }
                        ],
                        "arp": {
                            "timeout": 14400,
                            "learn-unsolicited": true,
                            "evpn": {
                                "advertise": [
                                    {
                                        "route-type": "static"
                                    },
                                    {
                                        "route-type": "dynamic"
                                    }
                                ]
                            }
                        }
                    },
                    "ipv6": {
                        "admin-state": "enable",
                        "address": [
                            {
                                "ip-prefix": "fd00:fde8:0:30::1/64",
                                "anycast-gw": true
                            }
                        ],
                        "neighbor-discovery": {
                            "learn-unsolicited": "global",
                            "evpn": {
                                "advertise": [
                                    {
                                        "route-type": "static"
                                    },
                                    {
                                        "route-type": "dynamic"
                                    }
                                ]
                            }
                        }
                    },
                    "anycast-gw": {
                        "virtual-router-id": 1
                    }
                }
            ]
        }
---
# configlet to tie the IRB to the GRT
apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: netinst-default-irb1
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  endpointSelector:
    - eda.nokia.com/role=leaf
  operatingSystem: srl
  configs:
    - path: .network-instance{.name=="default"}
      operation: Create
      config: |-
        {
            "interface": [
                {
                    "name": "irb1.1"
                }
            ]
        }
---
# configlet to tie the IRB to MACVRF-1
apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: netinst-macvrf1-irb1
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  endpointSelector:
    - eda.nokia.com/role=leaf
  operatingSystem: srl
  configs:
    - path: .network-instance{.name=="macvrf1"}
      operation: Create
      config: |-
        {
            "interface": [
                {
                    "name": "irb1.1"
                }
            ]
        }
