{
 "title": "SReXperts 2023",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(source)" } },
   {
    "name": "Network_Instance",
    "label": "Network_Instance",
    "query": {
     "query": "label_values(router_router_name)"
    }
   },
   {
    "name": "Interface",
    "label": "Interface",
    "query": {
     "query": "label_values(interface_interface_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Monitoring Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (source) (state_system_cpu_summary_usage_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "count by (source) (state_system_cpu_summary_usage_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_port_statistics_in_octets[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_port_statistics_out_octets[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top CPU Utilized Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(1, state_system_cpu_summary_usage_cpu_usage{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Current Memory In Use",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "State for $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Interface" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "state_system_cpu_summary_usage_cpu_usage{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Current Memory In Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Current Memory In Use",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "state_system_memory_pools_summary_total_in_use{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(state_port_statistics_in_unicast_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(state_port_statistics_out_unicast_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(state_router_interface_statistics_ip_in_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(state_router_interface_statistics_ip_out_packets{source=\"$Node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of BGP Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "state_router_bgp_statistics_peers{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Active Routes ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_router_bgp_neighbor_statistics_family_prefix_ipv4_active{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Active Routes ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_router_bgp_neighbor_statistics_family_prefix_ipv4_active{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Received Routes ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_router_bgp_neighbor_statistics_family_prefix_ipv4_received{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Neighbors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_router_bgp_convergence_family_up_peers{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Sent Routes ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "state_router_bgp_neighbor_statistics_family_prefix_ipv4_sent{source=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ISIS Control Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "state_router_isis_interface_level_statistics_packets_lsp{source=\"$Node\"}",
     "legendFormat": "{{ISIS-LSP}}"
    },
    {
     "expr": "state_router_isis_interface_level_statistics_packets_csnp{source=\"$Node\"}",
     "legendFormat": "{{ISIS-CSNP}}"
    },
    {
     "expr": "state_router_isis_interface_level_statistics_packets_psnp{source=\"$Node\"}",
     "legendFormat": "{{ISIS-PSNP}}"
    },
    {
     "expr": "state_router_isis_interface_level_statistics_packets_hello{source=\"$Node\"}",
     "legendFormat": "{{ISIS-Hello}}"
    }
   ]
  }
 ]
}