{
 "title": "SROS Telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(source)" } },
   { "name": "PortID", "query": { "query": "label_values(port_port_id)" } }
  ]
 },
 "panels": [
  { "title": "System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Memory Pools",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_total_in_use",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\", source=\"$Node\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_available_memory{source=\"$Node\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "-1*system_memory_pools_summary_total_in_use{source=\"$Node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Details for : $Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Port Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_oper_state{source=\"$Node\"}",
     "legendFormat": "{{port_port_id}}"
    }
   ]
  },
  {
   "title": "L2 Port Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(port_statistics_in_octets{source=\"$Node\"}[$__rate_interval])*8",
     "legendFormat": "{{port_port_id}} in"
    },
    {
     "expr": "-rate(port_statistics_out_octets{source=\"$Node\"}[$__rate_interval])*8",
     "legendFormat": "{{port_port_id}} out"
    }
   ]
  },
  {
   "title": "IP Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(router_interface_statistics_ip_in_octets{source=\"$Node\"}[$__interval])*8",
     "legendFormat": "{{interface_interface_name}}"
    },
    {
     "expr": "-rate(router_interface_statistics_ip_out_octets{source=\"$Node\"}[$__interval])*8",
     "legendFormat": "{{interface_interface_name}}"
    }
   ]
  },
  {
   "title": "MPLS Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(router_interface_statistics_mpls_in_octets{source=\"$Node\"}[$__interval])*8",
     "legendFormat": "{{interface_interface_name}}"
    },
    {
     "expr": "-rate(router_interface_statistics_mpls_out_octets{source=\"$Node\"}[$__interval])*8",
     "legendFormat": "{{interface_interface_name}}"
    }
   ]
  },
  { "title": "Port Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$PortID traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(port_statistics_in_unicast_packets{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Unicast In"
    },
    {
     "expr": "rate(port_statistics_in_broadcast_packets{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Broadcast In"
    },
    {
     "expr": "rate(port_statistics_in_multicast_packets{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Multicast In"
    },
    {
     "expr": "rate(port_statistics_in_errors{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Errors In"
    },
    {
     "expr": "rate(port_statistics_in_discards{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Discards In"
    },
    {
     "expr": "rate(port_statistics_out_unicast_packets{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Unicast Out"
    },
    {
     "expr": "rate(port_statistics_out_broadcast_packets{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Broadcast Out"
    },
    {
     "expr": "rate(port_statistics_out_multicast_packets{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Multicast Out"
    },
    {
     "expr": "rate(port_statistics_out_errors{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Errors Out"
    },
    {
     "expr": "rate(port_statistics_out_discards{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "Discards Out"
    }
   ]
  },
  {
   "title": "$PortID packet size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_64{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "64"
    },
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_65_to_127{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "65 to 127"
    },
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_128_to_255{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "128 to 255"
    },
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_256_to_511{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "256 to 511"
    },
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_512_to_1023{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "512 to 1023"
    },
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_1024_to_1518{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "1024 to 1518"
    },
    {
     "expr": "rate(port_ethernet_statistics_packet_size_octets_1519_to_max{source=\"$Node\", port_port_id=\"$PortID\"}[$__rate_interval])",
     "legendFormat": "1519 to max"
    }
   ]
  },
  { "title": "Route-Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Route Table",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_route_table_unicast_active_routes{source=\"$Node\", router_router_name=\"Base\"}",
     "legendFormat": "{{ family }} {{ protocol }} "
    }
   ]
  },
  {
   "title": "Route Table",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(router_route_table_unicast_active_routes{source=\"$Node\", family=\"ipv4\",router_router_name=\"Base\"})",
     "legendFormat": "IPv4"
    },
    {
     "expr": "sum(router_route_table_unicast_active_routes{source=\"$Node\", family=\"ipv6\",router_router_name=\"Base\"})",
     "legendFormat": "IPv6"
    }
   ]
  },
  { "title": "BGP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "BGP routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "router_bgp_statistics_routes_per_family_remote_routes{source=\"$Node\"}",
     "legendFormat": "{{ family }} RIB-In"
    },
    {
     "expr": "router_bgp_statistics_routes_per_family_remote_active_routes{source=\"$Node\"}",
     "legendFormat": "{{ family }} FIB"
    }
   ]
  },
  {
   "title": "BGP summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_active{source=\"$Node\", family=~\"ipv4|ipv6|evpn|vpn-ipv4|vpn-ipv6\"}",
     "legendFormat": "{{ neighbor_ip_address }} {{ family }} active "
    },
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_backup{source=\"$Node\", family=~\"ipv4|ipv6|evpn|vpn-ipv4|vpn-ipv6\"}",
     "legendFormat": "{{ neighbor_ip_address }} {{ family }} backup"
    },
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_received{source=\"$Node\", family=~\"ipv4|ipv6|evpn|vpn-ipv4|vpn-ipv6\"}",
     "legendFormat": "{{ neighbor_ip_address }} {{ family }} received"
    },
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_suppressed{source=\"$Node\", family=~\"ipv4|ipv6|evpn|vpn-ipv4|vpn-ipv6\"}",
     "legendFormat": "{{ neighbor_ip_address }} {{ family }} suppressed"
    },
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_rejected{source=\"$Node\", family=~\"ipv4|ipv6|evpn|vpn-ipv4|vpn-ipv6\"}",
     "legendFormat": "{{ neighbor_ip_address }} {{ family }} rejected"
    },
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_sent{source=\"$Node\", family=~\"ipv4|ipv6|evpn|vpn-ipv4|vpn-ipv6\"}",
     "legendFormat": "{{ neighbor_ip_address }} {{ family }} sent"
    }
   ]
  },
  {
   "title": "Total BGP messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(router_bgp_neighbor_statistics_received_messages{source=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(router_bgp_neighbor_statistics_sent_messages{source=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "BGP messages per neighbor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "topk(10, rate(router_bgp_neighbor_statistics_received_messages{source=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "{{neighbor_ip_address}} received"
    },
    {
     "expr": "-topk(10, rate(router_bgp_neighbor_statistics_sent_messages{source=\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Paths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "router_bgp_statistics_bgp_paths{source=\"$Node\"}",
     "legendFormat": "BGP Paths"
    }
   ]
  }
 ]
}