# Copyright 2024 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# Nokia SROS Ansible Automation Modules for SReXperts 2024
# Authors: Mohammad Zaman (mohammad.zaman@nokia.com), Thomas Hendriks (thomas.hendriks@nokia.com)

# Ansible playbook to configure Nokia SROS over NetConf Interface

# This role will push IP-Filter Config to the node
- name: Configuring ACL IP-Filters
  hosts: p1
  gather_facts: false
  roles:
    - filter
  tags: ['filter']


# This role will configure IP-Filter under L3 Interfaces
- name: Configuring IP Interface
  hosts: p1
  gather_facts: false
  roles:
    - interface
  tags: ['interface']
