# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

services:
  notebook:
    image: quay.io/jupyter/minimal-notebook:latest
    env_file: ./.env
    user: jovyan
    volumes:
      - ./:/srexperts/:ro
      - python_cache:/home/jovyan/
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    ports:
      - 8888:8888
    working_dir: "/srexperts"
    command: "start-notebook.sh /srexperts --NotebookApp.default_url='/lab/tree/pysros_primer.ipynb' --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.autoreload=True"
    networks:
      - srexperts

volumes:
  python_cache:

networks:
  srexperts:
    name: srexperts
    external: true
    