# Copyright 2024 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
- name: "Generate Filter Configuration XML"
  connection: local
  template: src=filter.j2 backup=no dest={{ playbook_dir }}/roles/filter/files/filter-{{ inventory_hostname }}.xml
  
- name: Loading configuration with netconf
  connection: netconf
  ansible.netcommon.netconf_config:
     content: "{{ lookup('file', './filter-{{ inventory_hostname }}.xml') }}"




