# Copyright 2025 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
name: Publish docs
on:
  workflow_dispatch:

env:
  MKDOCS_MATERIAL_VER: 9.6.1-insiders-4.53.15-hellt # insiders version

jobs:
  publish-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker run --env CI=true -v $(pwd):/docs --entrypoint mkdocs ghcr.io/srexperts/mkdocs-material-insiders:$MKDOCS_MATERIAL_VER gh-deploy --force
